---
title: "Check results without MM PAS"
author: "Briana Mittleman"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this analysis, I will test my results simply removing the PAS noted as affected by mutimapping. This is not perfect because I am not recalculating usage but I will be reasured that results will be robust when I rerun the pipeline.  

```{r}
library(tidyverse)
library(workflowr)
```


Load multimapping  



```{r}
ChimpMM=read.table("../data/multimap/Chimp_Uniq_multimapPAS.txt", stringsAsFactors = F, header = T)
HumanMM=read.table("../data/multimap/Human_Uniq_multimapPAS.txt", stringsAsFactors = F, header = T)
BothMM=read.table("../data/multimap/Both_multimapPAS.txt",stringsAsFactors = F, header = T)


AllMM=ChimpMM %>% bind_rows(HumanMM) %>% bind_rows(BothMM)

```



##Dominant PAS  

I will remove these and reasess shared dominant PAS.  

```{r}
PAS=read.table("../data/PAS_doubleFilter/PAS_10perc_either_HumanCoord_BothUsage_meta_doubleFilter.txt", header = T, stringsAsFactors = F) %>% anti_join(AllMM, by="PAS") %>% filter(!grepl("SNO", gene))

```

```{r}

chimpPASwMean =PAS %>% dplyr::select(-Human)
HumanPASwMean =PAS %>% dplyr::select(-Chimp)


Chimp_Dom= chimpPASwMean %>%
  group_by(gene) %>%
  arrange(desc(Chimp)) %>% 
  slice(1) %>% 
  group_by(gene) %>% 
  mutate(npas=n()) %>% 
  dplyr::select(gene,loc,PAS,Chimp) %>% 
  rename(ChimpLoc=loc, ChimpPAS=PAS)

Human_Dom= HumanPASwMean %>%
  group_by(gene) %>%
  arrange(desc(Human)) %>% 
  slice(1) %>% 
  group_by(gene) %>% 
  mutate(npas=n()) %>% 
  dplyr::select(gene,loc,PAS,Human) %>% 
  rename(HumanLoc=loc, HumanPAS=PAS)
```

```{r}
BothDom= Chimp_Dom %>% inner_join(Human_Dom,by="gene")
nrow(BothDom)
SameDom= BothDom %>% filter(ChimpPAS==HumanPAS)

nrow(SameDom)
```

```{r}
ggplot(SameDom, aes(x=HumanLoc))+ geom_histogram(stat="count") + labs(x="Location", y="Number of Genes", title="Dominant PAS for genes with matching by species")
```


Usage for these:  

```{r}
SameDom_gather=SameDom %>% dplyr::select(gene, HumanLoc, Chimp,Human) %>% gather(species, value, -c(gene,HumanLoc))

ggplot(SameDom_gather,aes(x=HumanLoc, y=value,fill=species)) + geom_boxplot() + scale_fill_brewer(palette = "Dark2") + labs(x="PAS Location", y="Mean Usage accross individuals", title="Mean usage for Genes with matching Dominant PAS")
```

```{r}
DiffDom=BothDom %>% filter(ChimpPAS!=HumanPAS)

nrow(DiffDom)
```

```{r}
DiffDom_g= DiffDom %>% select(gene, ChimpLoc, HumanLoc) %>% gather("Species", "Location", -gene)
ggplot(DiffDom_g,aes(by=Species, x=Location, fill=Species))+ geom_histogram(stat="count",position = "dodge") + labs(x="Location", y="Number of Genes", title="Different Dominant PAS \n (n=1937)") + scale_fill_brewer(palette = "Dark2")+theme(legend.position='bottom')
```

