---
title: "Dominant PAS, dribo, dprot"
author: "Briana Mittleman"
date: "4/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(workflowr)
library(tidyverse)
```

```{r}
FourRes=read.table("../data/DomStructure_4/InclusiveDominantPASat4.txt", header = T,stringsAsFactors = F)
FourRes_diff= FourRes %>% filter(Set=="Different")
FourRes_same= FourRes %>% filter(Set=="Same")
```

```{r}
#prot
ProteinSig=read.table("../data/Khan_prot/HC_SigProtein.txt", header = T, stringsAsFactors = F)%>% dplyr::rename("gene"=gene.symbol)
ProteinAll=read.table("../data/Khan_prot/HC_AlltestedProtein.txt", header = T, stringsAsFactors = F)
nameID=read.table("../../genome_anotation_data/ensemble_to_genename.txt",sep="\t", header = T, stringsAsFactors = F) %>% dplyr::select(Gene_stable_ID, Gene.name)

#ribo
Ribo=read.table("../data/Wang_ribo/HC_SigTranslation.txt",header = T, stringsAsFactors = F) 

RiboAll=read.table("../data/Wang_ribo/HC_AllTestedTranslation.txt",header = T, stringsAsFactors = F) 
```

```{r}
x=length(intersect(FourRes_diff$gene,ProteinSig$gene))
m=nrow(ProteinSig)
n=nrow(ProteinAll) - nrow(ProteinSig)
k=nrow(FourRes %>% filter(Set=="Different"))
N=nrow(ProteinAll)
phyper(x,m,n,k,lower.tail=F)
(x/k)/(m/N)

```


```{r}
x=length(intersect(FourRes_diff$gene,Ribo$gene))
m=nrow(Ribo)
n=nrow(RiboAll) - nrow(Ribo)
k=nrow(FourRes %>% filter(Set=="Different"))
N=nrow(RiboAll)
phyper(x,m,n,k,lower.tail=F)
(x/k)/(m/N)

```


Neither of these are singificant. 

Condition on tested in both:  

```{r}
Prot= ProteinAll %>% select(gene.symbol) %>% rename(gene=gene.symbol) %>% mutate(DP=ifelse(gene %in% ProteinSig$gene,"Yes","No"))
ProtDom= FourRes %>% select(gene,Set) %>% inner_join(Prot, by="gene")

x=nrow(ProtDom %>% filter(Set=="Different", DP=="Yes"))
m=nrow(ProtDom %>% filter( DP=="Yes"))
n=nrow(ProtDom %>% filter( DP=="No"))
k=nrow(ProtDom %>% filter(Set=="Different"))
N=nrow(ProtDom)
phyper(x,m,n,k,lower.tail=F)
(x/k)/(m/N)
```
```{r}
RiboSets= RiboAll %>% select(Gene) %>% rename(gene=Gene) %>% mutate(DR=ifelse(gene %in% ProteinSig$Gene,"Yes","No"))
RiboSetsDom= FourRes %>% select(gene,Set) %>% inner_join(RiboSets, by="gene")

x=nrow(RiboSetsDom %>% filter(Set=="Different", DR=="Yes"))
m=nrow(RiboSetsDom %>% filter( DR=="Yes"))
n=nrow(RiboSetsDom %>% filter( DR=="No"))
k=nrow(RiboSetsDom %>% filter(Set=="Different"))
N=nrow(RiboSetsDom)
phyper(x,m,n,k,lower.tail=F)
(x/k)/(m/N)
```

None of the dominant have DR.  

