---
title: "Normalize Phenotypes Nuclear"
author: "Briana Mittleman"
date: "10/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggpubr)
library(tidyverse)
library(reshape2)
```



```{r}
humanPheno=read.table("../data/Pheno_5perc/ALLPAS_postLift_LocParsed_Human_Pheno_5perc.txt",stringsAsFactors = F, header = T)
chimpPheno=read.table("../data/Pheno_5perc/ALLPAS_postLift_LocParsed_Chimp_Pheno_5perc.txt",stringsAsFactors = F, header = T)


allPhenoN=humanPheno %>% full_join(chimpPheno,by="chrom") %>% select(-contains("_T"))
```


```{bash,eval=F}
mkdir ../data/Pheno_5perc_nuclear
```

```{r}
write.table(allPhenoN, "../data/Pheno_5perc_nuclear/ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt", col.names = T, row.names = F, quote = F)

```


```{bash,eval=F}

gzip ../data/Pheno_5perc_nuclear/ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt

#conda deactivate 
conda deactivate 
conda deactivate 
#python 2
source ~/activate_anaconda_python2.sh 
#go to directory ../data/Pheno_5perc_nuclear/
python ../../code/prepare_phenotype_table.py ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt.gz
cat ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt.gz.phen_chr* > ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt.gz.phen_AllChrom
```


Use these normalized phenotypes for the PCA 

```{r}
metaDataN=read.table("../data/metadata_HCpanel.txt", header = T, stringsAsFactors = F) %>% filter(Fraction=="Nuclear")
```


```{r}
normPheno=read.table("../data/Pheno_5perc_nuclear/ALLPAS_postLift_LocParsed_bothSpecies_pheno_5perc_Nuclear.txt.gz.phen_AllChrom", col.names = c('Chr',	'start',	'end',	'ID',	'18498_N',		'18499_N',		'18502_N',		'18504_N',	'18510_N',	'18523_N',	'18358_N','3622_N',		'3659_N',	'4973_N',	'pt30_N',		'pt91_N'))

normPheno_matrix=as.matrix(normPheno %>% select(-Chr, -start, -end, -ID))
```

Run PCA:  

```{r}
pca_Pheno=prcomp(t(normPheno_matrix), center=T,scale=T)
pca_df=as.data.frame(pca_Pheno$rotation) %>% rownames_to_column(var="ID")

```









