---
title: "Number of PAS by Species - double filter"
author: "Briana Mittleman"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(cowplot)
library(tidyverse)
library(reshape2)
library(workflowr)
```


###Nuclear fraction
In this analysis I will look at thenumber of PAS per species at a gene level. I am only including PAS in chr1-22. These results use mean usage accross fraction.  

```{r}
PAS=read.table("../data/PAS_doubleFilter/PAS_5perc_either_HumanCoord_BothUsage_meta_doubleFilter.txt", stringsAsFactors = F, header = T)
```


I am looking at PAS at .05 or greater in either species. 
```{r}
PAS_sm=PAS %>% dplyr::select(gene, Chimp, Human) 

PAS_m= melt(PAS_sm, id.var="gene", variable.name="species", value.name="meanUsage") %>% filter(meanUsage >=0.05) %>% group_by(species, gene) %>% summarise(nPAS=n())

#pos = more human, neg = more chimp 
PAS_spread=PAS_m %>% spread(species, nPAS, fill=0) %>% mutate(DiffPAS=Human-Chimp)
```

```{r}
summary(PAS_spread$DiffPAS)

#more human
nrow(PAS_spread[PAS_spread$DiffPAS>0,])

#more chimp
nrow(PAS_spread[PAS_spread$DiffPAS<0,])

#same
nrow(PAS_spread[PAS_spread$DiffPAS==0,])

#all
nrow(PAS_spread)
```


```{r}

ggplot(PAS_spread, aes(x=DiffPAS)) + geom_bar(stat="count") +geom_vline(xintercept = mean(PAS_spread$DiffPAS),col="red") + labs(title="Difference in number of PAS at 5% Human vs Chimp", y="Genes", x="N Human PAS - N Chimp PAS")

```

```{r}
pdf("../output/supplement/Fig1_figSup6.pdf", height=4, width=4)
ggplot(PAS_spread, aes(x=DiffPAS)) + geom_bar(stat="count") +geom_vline(xintercept = mean(PAS_spread$DiffPAS),col="red") + labs(title="Difference in number of PAS at 5% \nHuman vs Chimpanzee", y="Genes", x="N Human PAS - N Chimpanzee PAS")+ theme_classic()+theme(axis.text.x = element_text(size=10),plot.title = element_text(hjust = 0.5, face="bold"),axis.text.y = element_text(size=10),text=element_text(size=10), legend.position = "top",plot.margin = unit(c(0,0,0,0), "cm"))
dev.off()


```



Plot distribution of N pas by species:  

Wilcoxan test to see if there is a difference in this distribution.  

```{r}
ChimpNPAS=PAS_m %>% filter(species=="Chimp")
HumanNPAS=PAS_m %>% filter(species=="Human")


wilcox.test(HumanNPAS$nPAS,ChimpNPAS$nPAS )
```
```{r}

PAS_m$nPAS=as.factor(PAS_m$nPAS)
ggplot(PAS_m,aes(x=nPAS, by=species, fill=species)) + geom_histogram(stat="count",position = "dodge") +  scale_fill_brewer(palette = "Dark2") + labs(title="Distribution for number of PAS at 5% ", x="Number of PAS",y="Genes")
```

```{r}
PAS_m %>% group_by(species) %>% summarise(meanPer=mean(nPAS))
```


