---
title: "Try quantile normalization"
author: "Briana Mittleman"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Try quantile normalization on the PAS between species. See how this affects the dominant pas. 


```{r}
library(ggpubr)
library(tidyverse)
library(gplots)
library("scales")
library("RColorBrewer")
library(edgeR)
```




I need a matrix with counts for all of the PAS. 
```{r}
PASMeta=read.table("../data/PAS_doubleFilter/PAS_10perc_either_HumanCoord_BothUsage_meta_doubleFilter.txt",header = T,stringsAsFactors = F) %>% select(PAS)
PASGene=read.table("../data/PAS_doubleFilter/PAS_10perc_either_HumanCoord_BothUsage_meta_doubleFilter.txt",header = T,stringsAsFactors = F) %>% select(PAS,gene,loc)


humanPAS=read.table("../Human/data/CleanLiftedPeaks_FC/ALLPAS_postLift_LocParsed_Human_fixed.fc", header=T, stringsAsFactors = F) %>% 
  separate(Geneid, into=c("disc","PAS","chrom", "start","end","strand","geneid"), sep=":") %>% 
  select(PAS, contains("_N")) %>% 
  inner_join(PASMeta, by="PAS")

chimpPAS=read.table("../Chimp/data/CleanLiftedPeaks_FC/ALLPAS_postLift_LocParsed_Chimp_fixed.fc", header=T, stringsAsFactors = F) %>% 
  separate(Geneid, into=c("disc","PAS","chrom", "start","end","strand","geneid"), sep=":") %>% 
  select(PAS, contains("_N")) %>% 
  inner_join(PASMeta,by="PAS")


BothPAScounts=humanPAS %>% inner_join(chimpPAS, by="PAS")

BothPAScountsM=as.matrix(BothPAScounts %>% column_to_rownames(var="PAS"))
```


```{r}
metadata=read.table("../data/metadata_HCpanel.txt",header = T) %>% mutate(id2=ifelse(grepl("pt", ID), ID, paste("X", ID, sep=""))) %>% filter(Fraction=="Nuclear")

order=c(metadata$id2[1:10], "pt30_N", "pt91_N")
```

```{r}
Species <- factor(metadata$Species)
design <- model.matrix(~ 0 + Species)
Counts.voom<- voom(BothPAScountsM, design, normalize.method="quantile", plot=T)


colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)

pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))
labels <- paste(metadata$Species,metadata$Line, sep=" ")



boxplot(Counts.voom$E, col = pal[as.numeric(metadata$Species)],las=2)
```
Find the most dominant with these

```{r}
NormCountsHuman= as.data.frame(Counts.voom$E) %>%
  select("X18498_N", "X18499_N", "X18502_N" ,"X18504_N", "X18510_N" ,"X18523_N" ) %>% 
  mutate(PAS=rownames(BothPAScountsM)) %>% 
  gather("Ind","NormCount", -PAS) %>% 
  group_by(PAS) %>% 
  summarise(HumanMean=mean(NormCount)) %>% 
  ungroup() %>% 
  inner_join(PASGene,by="PAS") %>% 
  group_by(gene) %>% 
  top_n(1,HumanMean) %>% 
  rename(HumanLoc=loc,HumanPAS=PAS)


NormCountsChimp= as.data.frame(Counts.voom$E) %>%
  select("X18358_N", "X3622_N" , "X3659_N", "X4973_N",  "pt30_N",   "pt91_N" ) %>% 
  mutate(PAS=rownames(BothPAScountsM)) %>% 
  gather("Ind","NormCount", -PAS) %>% 
  group_by(PAS) %>% 
  summarise(ChimpMean=mean(NormCount)) %>% 
  ungroup() %>% 
  inner_join(PASGene,by="PAS") %>% 
  group_by(gene) %>% 
  top_n(1,ChimpMean) %>% 
  rename(ChimpLoc=loc,ChimpPAS=PAS)

BothDom= NormCountsChimp %>% inner_join(NormCountsHuman,by="gene")
nrow(BothDom)
```
```{r}
SameDom=BothDom %>% filter(ChimpPAS==HumanPAS)
nrow(SameDom)
ggplot(SameDom, aes(x=HumanLoc))+ geom_histogram(stat="count") + labs(x="Location", y="Number of Genes", title="Dominant PAS for genes with matching by species \n quantile normalization (n=7094)")
```

```{r}
ggplot(SameDom, aes(x=HumanMean,y=ChimpMean)) + geom_point(alpha=.5) + geom_abline(aes(slope=1, intercept=0), color="blue")

```
```{r}
DiffDom=BothDom %>% filter(ChimpPAS!=HumanPAS)
nrow(DiffDom)

```

```{r}
DiffDom_g= DiffDom %>% select(gene, ChimpLoc, HumanLoc) %>% gather("Species", "Location", -gene)
ggplot(DiffDom_g,aes(by=Species, x=Location, fill=Species))+ geom_histogram(stat="count",position = "dodge") + labs(x="Location", y="Number of Genes", title="Different Dominant PAS \n Quantile Normalized (n=2753)") + scale_fill_brewer(palette = "Dark2")+theme(legend.position='bottom')
```


Plot PAS mean usage by location: 


```{r}

```

look at mean usage for all PAS by location: 

```{r}
NormCountsHumanAll= as.data.frame(Counts.voom$E) %>%
  select("X18498_N", "X18499_N", "X18502_N" ,"X18504_N", "X18510_N" ,"X18523_N" ) %>% 
  mutate(PAS=rownames(BothPAScountsM)) %>% 
  gather("Ind","NormCount", -PAS) %>% 
  group_by(PAS) %>% 
  summarise(Human=mean(NormCount))

NormCountsChimpAll= as.data.frame(Counts.voom$E) %>%
  select("X18358_N", "X3622_N" , "X3659_N", "X4973_N",  "pt30_N",   "pt91_N" ) %>% 
  mutate(PAS=rownames(BothPAScountsM)) %>% 
  gather("Ind","NormCount", -PAS) %>% 
  group_by(PAS) %>% 
  summarise(Chimp=mean(NormCount))


AllPASNorm=NormCountsChimpAll %>% inner_join(NormCountsHumanAll, by="PAS") %>% inner_join(PASGene,by="PAS")
```


```{r}

AllPASNorm_g= AllPASNorm %>% gather("Species", "NormPASMean",-PAS,-gene,-loc)

ggplot(AllPASNorm_g,aes(x=loc, by=Species, y=NormPASMean,fill=Species)) +geom_boxplot()+scale_fill_brewer(palette = "Dark2") +stat_compare_means(label = "p.signif")+ labs(title="Quantile Normalized mean usage for all PAS")
```

